// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: protos/Auth.proto
// </auto-generated>
#pragma warning disable 0414, 1591, 8981
#region Designer generated code

using grpc = global::Grpc.Core;

namespace EntryPoints.Grpc.Dtos.Protos {
  public static partial class Auth
  {
    static readonly string __ServiceName = "Auth";

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::EntryPoints.Grpc.Dtos.Protos.UsuarioProto> __Marshaller_UsuarioProto = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::EntryPoints.Grpc.Dtos.Protos.UsuarioProto.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::EntryPoints.Grpc.Dtos.Protos.RespuestaAuth> __Marshaller_RespuestaAuth = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::EntryPoints.Grpc.Dtos.Protos.RespuestaAuth.Parser));

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::EntryPoints.Grpc.Dtos.Protos.UsuarioProto, global::EntryPoints.Grpc.Dtos.Protos.RespuestaAuth> __Method_CrearUsuario = new grpc::Method<global::EntryPoints.Grpc.Dtos.Protos.UsuarioProto, global::EntryPoints.Grpc.Dtos.Protos.RespuestaAuth>(
        grpc::MethodType.Unary,
        __ServiceName,
        "CrearUsuario",
        __Marshaller_UsuarioProto,
        __Marshaller_RespuestaAuth);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::EntryPoints.Grpc.Dtos.Protos.UsuarioProto, global::EntryPoints.Grpc.Dtos.Protos.RespuestaAuth> __Method_IniciarSesion = new grpc::Method<global::EntryPoints.Grpc.Dtos.Protos.UsuarioProto, global::EntryPoints.Grpc.Dtos.Protos.RespuestaAuth>(
        grpc::MethodType.Unary,
        __ServiceName,
        "IniciarSesion",
        __Marshaller_UsuarioProto,
        __Marshaller_RespuestaAuth);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::EntryPoints.Grpc.Dtos.Protos.AuthReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of Auth</summary>
    [grpc::BindServiceMethod(typeof(Auth), "BindService")]
    public abstract partial class AuthBase
    {
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::EntryPoints.Grpc.Dtos.Protos.RespuestaAuth> CrearUsuario(global::EntryPoints.Grpc.Dtos.Protos.UsuarioProto request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::EntryPoints.Grpc.Dtos.Protos.RespuestaAuth> IniciarSesion(global::EntryPoints.Grpc.Dtos.Protos.UsuarioProto request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for Auth</summary>
    public partial class AuthClient : grpc::ClientBase<AuthClient>
    {
      /// <summary>Creates a new client for Auth</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public AuthClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for Auth that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public AuthClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected AuthClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected AuthClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::EntryPoints.Grpc.Dtos.Protos.RespuestaAuth CrearUsuario(global::EntryPoints.Grpc.Dtos.Protos.UsuarioProto request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CrearUsuario(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::EntryPoints.Grpc.Dtos.Protos.RespuestaAuth CrearUsuario(global::EntryPoints.Grpc.Dtos.Protos.UsuarioProto request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_CrearUsuario, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::EntryPoints.Grpc.Dtos.Protos.RespuestaAuth> CrearUsuarioAsync(global::EntryPoints.Grpc.Dtos.Protos.UsuarioProto request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CrearUsuarioAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::EntryPoints.Grpc.Dtos.Protos.RespuestaAuth> CrearUsuarioAsync(global::EntryPoints.Grpc.Dtos.Protos.UsuarioProto request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_CrearUsuario, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::EntryPoints.Grpc.Dtos.Protos.RespuestaAuth IniciarSesion(global::EntryPoints.Grpc.Dtos.Protos.UsuarioProto request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return IniciarSesion(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::EntryPoints.Grpc.Dtos.Protos.RespuestaAuth IniciarSesion(global::EntryPoints.Grpc.Dtos.Protos.UsuarioProto request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_IniciarSesion, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::EntryPoints.Grpc.Dtos.Protos.RespuestaAuth> IniciarSesionAsync(global::EntryPoints.Grpc.Dtos.Protos.UsuarioProto request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return IniciarSesionAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::EntryPoints.Grpc.Dtos.Protos.RespuestaAuth> IniciarSesionAsync(global::EntryPoints.Grpc.Dtos.Protos.UsuarioProto request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_IniciarSesion, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected override AuthClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new AuthClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static grpc::ServerServiceDefinition BindService(AuthBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_CrearUsuario, serviceImpl.CrearUsuario)
          .AddMethod(__Method_IniciarSesion, serviceImpl.IniciarSesion).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static void BindService(grpc::ServiceBinderBase serviceBinder, AuthBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_CrearUsuario, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::EntryPoints.Grpc.Dtos.Protos.UsuarioProto, global::EntryPoints.Grpc.Dtos.Protos.RespuestaAuth>(serviceImpl.CrearUsuario));
      serviceBinder.AddMethod(__Method_IniciarSesion, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::EntryPoints.Grpc.Dtos.Protos.UsuarioProto, global::EntryPoints.Grpc.Dtos.Protos.RespuestaAuth>(serviceImpl.IniciarSesion));
    }

  }
}
#endregion
