// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: protos/Cuentas.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace EntryPoints.Grpc.Dtos.Protos.Cuentas {

  /// <summary>Holder for reflection information generated from protos/Cuentas.proto</summary>
  public static partial class CuentasReflection {

    #region Descriptor
    /// <summary>File descriptor for protos/Cuentas.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static CuentasReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChRwcm90b3MvQ3VlbnRhcy5wcm90bxofZ29vZ2xlL3Byb3RvYnVmL3RpbWVz",
            "dGFtcC5wcm90byIrChNOdW1lcm9DdWVudGFSZXF1ZXN0EhQKDE51bWVyb2N1",
            "ZW50YRgBIAEoCSIpChRDdWVudGFDbGllbnRlUmVxdWVzdBIRCglJZENsaWVu",
            "dGUYASABKAkiIQoNQ3VlbnRhUmVxdWVzdBIQCghJZEN1ZW50YRgBIAEoCSJd",
            "CgtDdWVudGFQcm90bxIRCglJZENsaWVudGUYASABKAkSHwoKVGlwb0N1ZW50",
            "YRgCIAEoDjILLlRpcG9DdWVudGESDQoFU2FsZG8YAyABKAISCwoDR01GGAQg",
            "ASgIIs4BChBUcmFuc2FjY2lvblByb3RvEgoKAklkGAEgASgJEhcKD0lkQ3Vl",
            "bnRhRW1pc29yYRgCIAEoCRIZChFJZEN1ZW50YVJlY2VwdG9yYRgDIAEoCRIp",
            "Cg9UaXBvVHJhbnNhY2Npb24YBCABKA4yEC5UaXBvVHJhbnNhY2Npb24SDQoF",
            "VmFsb3IYBSABKAISFwoPRmVjaGFNb3ZpbWllbnRvGAYgASgJEicKDlRpcG9N",
            "b3ZpbWllbnRvGAcgASgOMg8uVGlwb01vdmltaWVudG8iUAoPUmVzcHVlc3Rh",
            "Q3VlbnRhEg8KB01lbnNhamUYASABKAkSDQoFRXJyb3IYAiABKAgSHQoERGF0",
            "YRgDIAEoCzIPLkN1ZW50YUNvbXBsZXRhIlYKFVJlc3B1ZXN0YUxpc3RhQ3Vl",
            "bnRhcxIPCgdNZW5zYWplGAEgASgJEg0KBUVycm9yGAIgASgIEh0KBERhdGEY",
            "AyADKAsyDy5DdWVudGFDb21wbGV0YSKcAgoOQ3VlbnRhQ29tcGxldGESCgoC",
            "SWQYASABKAkSFAoMTnVtZXJvQ3VlbnRhGAIgASgJEhEKCUlkQ2xpZW50ZRgD",
            "IAEoCRIfCgpUaXBvQ3VlbnRhGAQgASgOMgsuVGlwb0N1ZW50YRIjCgxFc3Rh",
            "ZG9DdWVudGEYBSABKA4yDS5Fc3RhZG9DdWVudGESDQoFU2FsZG8YBiABKAIS",
            "FwoPU2FsZG9EaXNwb25pYmxlGAcgASgCEgsKA0dNRhgIIAEoCBIVCg1GZWNo",
            "YUNyZWFjaW9uGAkgASgJEhkKEUZlY2hhTW9kaWZpY2FjaW9uGAogASgJEigK",
            "DVRyYW5zYWNjaW9uZXMYCyADKAsyES5UcmFuc2FjY2lvblByb3RvKicKClRp",
            "cG9DdWVudGESCgoGQUhPUlJPEAASDQoJQ09SUklFTlRFEAEqQgoPVGlwb1Ry",
            "YW5zYWNjaW9uEhEKDVRSQU5TRkVSRU5DSUEQABIQCgxDT05TSUdOQUNJT04Q",
            "ARIKCgZSRVRJUk8QAiopCg5UaXBvTW92aW1pZW50bxILCgdDUkVESVRPEAAS",
            "CgoGREVCSVRPEAEqNwoMRXN0YWRvQ3VlbnRhEgoKBkFDVElWQRAAEgwKCElO",
            "QUNUSVZBEAESDQoJQ0FOQ0VMQURBEAIyjwMKDUN1ZW50YVNlcnZpY2USLQoL",
            "Q3JlYXJDdWVudGESDC5DdWVudGFQcm90bxoQLlJlc3B1ZXN0YUN1ZW50YRIz",
            "Cg9PYnRlbmVyQ3VlbnRhSWQSDi5DdWVudGFSZXF1ZXN0GhAuUmVzcHVlc3Rh",
            "Q3VlbnRhEjUKEEFjdHVhbGl6YXJDdWVudGESDy5DdWVudGFDb21wbGV0YRoQ",
            "LlJlc3B1ZXN0YUN1ZW50YRIyCg5DYW5jZWxhckN1ZW50YRIOLkN1ZW50YVJl",
            "cXVlc3QaEC5SZXNwdWVzdGFDdWVudGESNgoSQWN0aXZhckN1ZW50YUFzeW5j",
            "Eg4uQ3VlbnRhUmVxdWVzdBoQLlJlc3B1ZXN0YUN1ZW50YRI9ChNPYnRlbmVy",
            "Q3VlbnRhTnVtZXJvEhQuTnVtZXJvQ3VlbnRhUmVxdWVzdBoQLlJlc3B1ZXN0",
            "YUN1ZW50YRI4ChRJbmFjdGl2YXJDdWVudGFBc3luYxIOLkN1ZW50YVJlcXVl",
            "c3QaEC5SZXNwdWVzdGFDdWVudGFCJ6oCJEVudHJ5UG9pbnRzLkdycGMuRHRv",
            "cy5Qcm90b3MuQ3VlbnRhc2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.TimestampReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::EntryPoints.Grpc.Dtos.Protos.Cuentas.TipoCuenta), typeof(global::EntryPoints.Grpc.Dtos.Protos.Cuentas.TipoTransaccion), typeof(global::EntryPoints.Grpc.Dtos.Protos.Cuentas.TipoMovimiento), typeof(global::EntryPoints.Grpc.Dtos.Protos.Cuentas.EstadoCuenta), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::EntryPoints.Grpc.Dtos.Protos.Cuentas.NumeroCuentaRequest), global::EntryPoints.Grpc.Dtos.Protos.Cuentas.NumeroCuentaRequest.Parser, new[]{ "Numerocuenta" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::EntryPoints.Grpc.Dtos.Protos.Cuentas.CuentaClienteRequest), global::EntryPoints.Grpc.Dtos.Protos.Cuentas.CuentaClienteRequest.Parser, new[]{ "IdCliente" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::EntryPoints.Grpc.Dtos.Protos.Cuentas.CuentaRequest), global::EntryPoints.Grpc.Dtos.Protos.Cuentas.CuentaRequest.Parser, new[]{ "IdCuenta" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::EntryPoints.Grpc.Dtos.Protos.Cuentas.CuentaProto), global::EntryPoints.Grpc.Dtos.Protos.Cuentas.CuentaProto.Parser, new[]{ "IdCliente", "TipoCuenta", "Saldo", "GMF" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::EntryPoints.Grpc.Dtos.Protos.Cuentas.TransaccionProto), global::EntryPoints.Grpc.Dtos.Protos.Cuentas.TransaccionProto.Parser, new[]{ "Id", "IdCuentaEmisora", "IdCuentaReceptora", "TipoTransaccion", "Valor", "FechaMovimiento", "TipoMovimiento" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::EntryPoints.Grpc.Dtos.Protos.Cuentas.RespuestaCuenta), global::EntryPoints.Grpc.Dtos.Protos.Cuentas.RespuestaCuenta.Parser, new[]{ "Mensaje", "Error", "Data" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::EntryPoints.Grpc.Dtos.Protos.Cuentas.RespuestaListaCuentas), global::EntryPoints.Grpc.Dtos.Protos.Cuentas.RespuestaListaCuentas.Parser, new[]{ "Mensaje", "Error", "Data" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::EntryPoints.Grpc.Dtos.Protos.Cuentas.CuentaCompleta), global::EntryPoints.Grpc.Dtos.Protos.Cuentas.CuentaCompleta.Parser, new[]{ "Id", "NumeroCuenta", "IdCliente", "TipoCuenta", "EstadoCuenta", "Saldo", "SaldoDisponible", "GMF", "FechaCreacion", "FechaModificacion", "Transacciones" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum TipoCuenta {
    [pbr::OriginalName("AHORRO")] Ahorro = 0,
    [pbr::OriginalName("CORRIENTE")] Corriente = 1,
  }

  public enum TipoTransaccion {
    [pbr::OriginalName("TRANSFERENCIA")] Transferencia = 0,
    [pbr::OriginalName("CONSIGNACION")] Consignacion = 1,
    [pbr::OriginalName("RETIRO")] Retiro = 2,
  }

  public enum TipoMovimiento {
    [pbr::OriginalName("CREDITO")] Credito = 0,
    [pbr::OriginalName("DEBITO")] Debito = 1,
  }

  public enum EstadoCuenta {
    [pbr::OriginalName("ACTIVA")] Activa = 0,
    [pbr::OriginalName("INACTIVA")] Inactiva = 1,
    [pbr::OriginalName("CANCELADA")] Cancelada = 2,
  }

  #endregion

  #region Messages
  /// <summary>
  ///
  ///message TransacccionSimpleRequest{
  ///string IdCuenta = 1;
  ///float Monto = 2;
  ///}
  /// </summary>
  public sealed partial class NumeroCuentaRequest : pb::IMessage<NumeroCuentaRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<NumeroCuentaRequest> _parser = new pb::MessageParser<NumeroCuentaRequest>(() => new NumeroCuentaRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<NumeroCuentaRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::EntryPoints.Grpc.Dtos.Protos.Cuentas.CuentasReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public NumeroCuentaRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public NumeroCuentaRequest(NumeroCuentaRequest other) : this() {
      numerocuenta_ = other.numerocuenta_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public NumeroCuentaRequest Clone() {
      return new NumeroCuentaRequest(this);
    }

    /// <summary>Field number for the "Numerocuenta" field.</summary>
    public const int NumerocuentaFieldNumber = 1;
    private string numerocuenta_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Numerocuenta {
      get { return numerocuenta_; }
      set {
        numerocuenta_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as NumeroCuentaRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(NumeroCuentaRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Numerocuenta != other.Numerocuenta) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Numerocuenta.Length != 0) hash ^= Numerocuenta.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Numerocuenta.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Numerocuenta);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Numerocuenta.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Numerocuenta);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Numerocuenta.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Numerocuenta);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(NumeroCuentaRequest other) {
      if (other == null) {
        return;
      }
      if (other.Numerocuenta.Length != 0) {
        Numerocuenta = other.Numerocuenta;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Numerocuenta = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Numerocuenta = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class CuentaClienteRequest : pb::IMessage<CuentaClienteRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<CuentaClienteRequest> _parser = new pb::MessageParser<CuentaClienteRequest>(() => new CuentaClienteRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<CuentaClienteRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::EntryPoints.Grpc.Dtos.Protos.Cuentas.CuentasReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CuentaClienteRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CuentaClienteRequest(CuentaClienteRequest other) : this() {
      idCliente_ = other.idCliente_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CuentaClienteRequest Clone() {
      return new CuentaClienteRequest(this);
    }

    /// <summary>Field number for the "IdCliente" field.</summary>
    public const int IdClienteFieldNumber = 1;
    private string idCliente_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string IdCliente {
      get { return idCliente_; }
      set {
        idCliente_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as CuentaClienteRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(CuentaClienteRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (IdCliente != other.IdCliente) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (IdCliente.Length != 0) hash ^= IdCliente.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (IdCliente.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(IdCliente);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (IdCliente.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(IdCliente);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (IdCliente.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(IdCliente);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(CuentaClienteRequest other) {
      if (other == null) {
        return;
      }
      if (other.IdCliente.Length != 0) {
        IdCliente = other.IdCliente;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            IdCliente = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            IdCliente = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class CuentaRequest : pb::IMessage<CuentaRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<CuentaRequest> _parser = new pb::MessageParser<CuentaRequest>(() => new CuentaRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<CuentaRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::EntryPoints.Grpc.Dtos.Protos.Cuentas.CuentasReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CuentaRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CuentaRequest(CuentaRequest other) : this() {
      idCuenta_ = other.idCuenta_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CuentaRequest Clone() {
      return new CuentaRequest(this);
    }

    /// <summary>Field number for the "IdCuenta" field.</summary>
    public const int IdCuentaFieldNumber = 1;
    private string idCuenta_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string IdCuenta {
      get { return idCuenta_; }
      set {
        idCuenta_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as CuentaRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(CuentaRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (IdCuenta != other.IdCuenta) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (IdCuenta.Length != 0) hash ^= IdCuenta.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (IdCuenta.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(IdCuenta);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (IdCuenta.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(IdCuenta);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (IdCuenta.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(IdCuenta);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(CuentaRequest other) {
      if (other == null) {
        return;
      }
      if (other.IdCuenta.Length != 0) {
        IdCuenta = other.IdCuenta;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            IdCuenta = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            IdCuenta = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class CuentaProto : pb::IMessage<CuentaProto>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<CuentaProto> _parser = new pb::MessageParser<CuentaProto>(() => new CuentaProto());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<CuentaProto> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::EntryPoints.Grpc.Dtos.Protos.Cuentas.CuentasReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CuentaProto() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CuentaProto(CuentaProto other) : this() {
      idCliente_ = other.idCliente_;
      tipoCuenta_ = other.tipoCuenta_;
      saldo_ = other.saldo_;
      gMF_ = other.gMF_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CuentaProto Clone() {
      return new CuentaProto(this);
    }

    /// <summary>Field number for the "IdCliente" field.</summary>
    public const int IdClienteFieldNumber = 1;
    private string idCliente_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string IdCliente {
      get { return idCliente_; }
      set {
        idCliente_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "TipoCuenta" field.</summary>
    public const int TipoCuentaFieldNumber = 2;
    private global::EntryPoints.Grpc.Dtos.Protos.Cuentas.TipoCuenta tipoCuenta_ = global::EntryPoints.Grpc.Dtos.Protos.Cuentas.TipoCuenta.Ahorro;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::EntryPoints.Grpc.Dtos.Protos.Cuentas.TipoCuenta TipoCuenta {
      get { return tipoCuenta_; }
      set {
        tipoCuenta_ = value;
      }
    }

    /// <summary>Field number for the "Saldo" field.</summary>
    public const int SaldoFieldNumber = 3;
    private float saldo_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float Saldo {
      get { return saldo_; }
      set {
        saldo_ = value;
      }
    }

    /// <summary>Field number for the "GMF" field.</summary>
    public const int GMFFieldNumber = 4;
    private bool gMF_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool GMF {
      get { return gMF_; }
      set {
        gMF_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as CuentaProto);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(CuentaProto other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (IdCliente != other.IdCliente) return false;
      if (TipoCuenta != other.TipoCuenta) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Saldo, other.Saldo)) return false;
      if (GMF != other.GMF) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (IdCliente.Length != 0) hash ^= IdCliente.GetHashCode();
      if (TipoCuenta != global::EntryPoints.Grpc.Dtos.Protos.Cuentas.TipoCuenta.Ahorro) hash ^= TipoCuenta.GetHashCode();
      if (Saldo != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Saldo);
      if (GMF != false) hash ^= GMF.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (IdCliente.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(IdCliente);
      }
      if (TipoCuenta != global::EntryPoints.Grpc.Dtos.Protos.Cuentas.TipoCuenta.Ahorro) {
        output.WriteRawTag(16);
        output.WriteEnum((int) TipoCuenta);
      }
      if (Saldo != 0F) {
        output.WriteRawTag(29);
        output.WriteFloat(Saldo);
      }
      if (GMF != false) {
        output.WriteRawTag(32);
        output.WriteBool(GMF);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (IdCliente.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(IdCliente);
      }
      if (TipoCuenta != global::EntryPoints.Grpc.Dtos.Protos.Cuentas.TipoCuenta.Ahorro) {
        output.WriteRawTag(16);
        output.WriteEnum((int) TipoCuenta);
      }
      if (Saldo != 0F) {
        output.WriteRawTag(29);
        output.WriteFloat(Saldo);
      }
      if (GMF != false) {
        output.WriteRawTag(32);
        output.WriteBool(GMF);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (IdCliente.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(IdCliente);
      }
      if (TipoCuenta != global::EntryPoints.Grpc.Dtos.Protos.Cuentas.TipoCuenta.Ahorro) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) TipoCuenta);
      }
      if (Saldo != 0F) {
        size += 1 + 4;
      }
      if (GMF != false) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(CuentaProto other) {
      if (other == null) {
        return;
      }
      if (other.IdCliente.Length != 0) {
        IdCliente = other.IdCliente;
      }
      if (other.TipoCuenta != global::EntryPoints.Grpc.Dtos.Protos.Cuentas.TipoCuenta.Ahorro) {
        TipoCuenta = other.TipoCuenta;
      }
      if (other.Saldo != 0F) {
        Saldo = other.Saldo;
      }
      if (other.GMF != false) {
        GMF = other.GMF;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            IdCliente = input.ReadString();
            break;
          }
          case 16: {
            TipoCuenta = (global::EntryPoints.Grpc.Dtos.Protos.Cuentas.TipoCuenta) input.ReadEnum();
            break;
          }
          case 29: {
            Saldo = input.ReadFloat();
            break;
          }
          case 32: {
            GMF = input.ReadBool();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            IdCliente = input.ReadString();
            break;
          }
          case 16: {
            TipoCuenta = (global::EntryPoints.Grpc.Dtos.Protos.Cuentas.TipoCuenta) input.ReadEnum();
            break;
          }
          case 29: {
            Saldo = input.ReadFloat();
            break;
          }
          case 32: {
            GMF = input.ReadBool();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class TransaccionProto : pb::IMessage<TransaccionProto>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<TransaccionProto> _parser = new pb::MessageParser<TransaccionProto>(() => new TransaccionProto());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<TransaccionProto> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::EntryPoints.Grpc.Dtos.Protos.Cuentas.CuentasReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TransaccionProto() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TransaccionProto(TransaccionProto other) : this() {
      id_ = other.id_;
      idCuentaEmisora_ = other.idCuentaEmisora_;
      idCuentaReceptora_ = other.idCuentaReceptora_;
      tipoTransaccion_ = other.tipoTransaccion_;
      valor_ = other.valor_;
      fechaMovimiento_ = other.fechaMovimiento_;
      tipoMovimiento_ = other.tipoMovimiento_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TransaccionProto Clone() {
      return new TransaccionProto(this);
    }

    /// <summary>Field number for the "Id" field.</summary>
    public const int IdFieldNumber = 1;
    private string id_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Id {
      get { return id_; }
      set {
        id_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "IdCuentaEmisora" field.</summary>
    public const int IdCuentaEmisoraFieldNumber = 2;
    private string idCuentaEmisora_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string IdCuentaEmisora {
      get { return idCuentaEmisora_; }
      set {
        idCuentaEmisora_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "IdCuentaReceptora" field.</summary>
    public const int IdCuentaReceptoraFieldNumber = 3;
    private string idCuentaReceptora_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string IdCuentaReceptora {
      get { return idCuentaReceptora_; }
      set {
        idCuentaReceptora_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "TipoTransaccion" field.</summary>
    public const int TipoTransaccionFieldNumber = 4;
    private global::EntryPoints.Grpc.Dtos.Protos.Cuentas.TipoTransaccion tipoTransaccion_ = global::EntryPoints.Grpc.Dtos.Protos.Cuentas.TipoTransaccion.Transferencia;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::EntryPoints.Grpc.Dtos.Protos.Cuentas.TipoTransaccion TipoTransaccion {
      get { return tipoTransaccion_; }
      set {
        tipoTransaccion_ = value;
      }
    }

    /// <summary>Field number for the "Valor" field.</summary>
    public const int ValorFieldNumber = 5;
    private float valor_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float Valor {
      get { return valor_; }
      set {
        valor_ = value;
      }
    }

    /// <summary>Field number for the "FechaMovimiento" field.</summary>
    public const int FechaMovimientoFieldNumber = 6;
    private string fechaMovimiento_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string FechaMovimiento {
      get { return fechaMovimiento_; }
      set {
        fechaMovimiento_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "TipoMovimiento" field.</summary>
    public const int TipoMovimientoFieldNumber = 7;
    private global::EntryPoints.Grpc.Dtos.Protos.Cuentas.TipoMovimiento tipoMovimiento_ = global::EntryPoints.Grpc.Dtos.Protos.Cuentas.TipoMovimiento.Credito;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::EntryPoints.Grpc.Dtos.Protos.Cuentas.TipoMovimiento TipoMovimiento {
      get { return tipoMovimiento_; }
      set {
        tipoMovimiento_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as TransaccionProto);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(TransaccionProto other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (IdCuentaEmisora != other.IdCuentaEmisora) return false;
      if (IdCuentaReceptora != other.IdCuentaReceptora) return false;
      if (TipoTransaccion != other.TipoTransaccion) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Valor, other.Valor)) return false;
      if (FechaMovimiento != other.FechaMovimiento) return false;
      if (TipoMovimiento != other.TipoMovimiento) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Id.Length != 0) hash ^= Id.GetHashCode();
      if (IdCuentaEmisora.Length != 0) hash ^= IdCuentaEmisora.GetHashCode();
      if (IdCuentaReceptora.Length != 0) hash ^= IdCuentaReceptora.GetHashCode();
      if (TipoTransaccion != global::EntryPoints.Grpc.Dtos.Protos.Cuentas.TipoTransaccion.Transferencia) hash ^= TipoTransaccion.GetHashCode();
      if (Valor != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Valor);
      if (FechaMovimiento.Length != 0) hash ^= FechaMovimiento.GetHashCode();
      if (TipoMovimiento != global::EntryPoints.Grpc.Dtos.Protos.Cuentas.TipoMovimiento.Credito) hash ^= TipoMovimiento.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      if (IdCuentaEmisora.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(IdCuentaEmisora);
      }
      if (IdCuentaReceptora.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(IdCuentaReceptora);
      }
      if (TipoTransaccion != global::EntryPoints.Grpc.Dtos.Protos.Cuentas.TipoTransaccion.Transferencia) {
        output.WriteRawTag(32);
        output.WriteEnum((int) TipoTransaccion);
      }
      if (Valor != 0F) {
        output.WriteRawTag(45);
        output.WriteFloat(Valor);
      }
      if (FechaMovimiento.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(FechaMovimiento);
      }
      if (TipoMovimiento != global::EntryPoints.Grpc.Dtos.Protos.Cuentas.TipoMovimiento.Credito) {
        output.WriteRawTag(56);
        output.WriteEnum((int) TipoMovimiento);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      if (IdCuentaEmisora.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(IdCuentaEmisora);
      }
      if (IdCuentaReceptora.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(IdCuentaReceptora);
      }
      if (TipoTransaccion != global::EntryPoints.Grpc.Dtos.Protos.Cuentas.TipoTransaccion.Transferencia) {
        output.WriteRawTag(32);
        output.WriteEnum((int) TipoTransaccion);
      }
      if (Valor != 0F) {
        output.WriteRawTag(45);
        output.WriteFloat(Valor);
      }
      if (FechaMovimiento.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(FechaMovimiento);
      }
      if (TipoMovimiento != global::EntryPoints.Grpc.Dtos.Protos.Cuentas.TipoMovimiento.Credito) {
        output.WriteRawTag(56);
        output.WriteEnum((int) TipoMovimiento);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Id.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Id);
      }
      if (IdCuentaEmisora.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(IdCuentaEmisora);
      }
      if (IdCuentaReceptora.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(IdCuentaReceptora);
      }
      if (TipoTransaccion != global::EntryPoints.Grpc.Dtos.Protos.Cuentas.TipoTransaccion.Transferencia) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) TipoTransaccion);
      }
      if (Valor != 0F) {
        size += 1 + 4;
      }
      if (FechaMovimiento.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(FechaMovimiento);
      }
      if (TipoMovimiento != global::EntryPoints.Grpc.Dtos.Protos.Cuentas.TipoMovimiento.Credito) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) TipoMovimiento);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(TransaccionProto other) {
      if (other == null) {
        return;
      }
      if (other.Id.Length != 0) {
        Id = other.Id;
      }
      if (other.IdCuentaEmisora.Length != 0) {
        IdCuentaEmisora = other.IdCuentaEmisora;
      }
      if (other.IdCuentaReceptora.Length != 0) {
        IdCuentaReceptora = other.IdCuentaReceptora;
      }
      if (other.TipoTransaccion != global::EntryPoints.Grpc.Dtos.Protos.Cuentas.TipoTransaccion.Transferencia) {
        TipoTransaccion = other.TipoTransaccion;
      }
      if (other.Valor != 0F) {
        Valor = other.Valor;
      }
      if (other.FechaMovimiento.Length != 0) {
        FechaMovimiento = other.FechaMovimiento;
      }
      if (other.TipoMovimiento != global::EntryPoints.Grpc.Dtos.Protos.Cuentas.TipoMovimiento.Credito) {
        TipoMovimiento = other.TipoMovimiento;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
          case 18: {
            IdCuentaEmisora = input.ReadString();
            break;
          }
          case 26: {
            IdCuentaReceptora = input.ReadString();
            break;
          }
          case 32: {
            TipoTransaccion = (global::EntryPoints.Grpc.Dtos.Protos.Cuentas.TipoTransaccion) input.ReadEnum();
            break;
          }
          case 45: {
            Valor = input.ReadFloat();
            break;
          }
          case 50: {
            FechaMovimiento = input.ReadString();
            break;
          }
          case 56: {
            TipoMovimiento = (global::EntryPoints.Grpc.Dtos.Protos.Cuentas.TipoMovimiento) input.ReadEnum();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
          case 18: {
            IdCuentaEmisora = input.ReadString();
            break;
          }
          case 26: {
            IdCuentaReceptora = input.ReadString();
            break;
          }
          case 32: {
            TipoTransaccion = (global::EntryPoints.Grpc.Dtos.Protos.Cuentas.TipoTransaccion) input.ReadEnum();
            break;
          }
          case 45: {
            Valor = input.ReadFloat();
            break;
          }
          case 50: {
            FechaMovimiento = input.ReadString();
            break;
          }
          case 56: {
            TipoMovimiento = (global::EntryPoints.Grpc.Dtos.Protos.Cuentas.TipoMovimiento) input.ReadEnum();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class RespuestaCuenta : pb::IMessage<RespuestaCuenta>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<RespuestaCuenta> _parser = new pb::MessageParser<RespuestaCuenta>(() => new RespuestaCuenta());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<RespuestaCuenta> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::EntryPoints.Grpc.Dtos.Protos.Cuentas.CuentasReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RespuestaCuenta() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RespuestaCuenta(RespuestaCuenta other) : this() {
      mensaje_ = other.mensaje_;
      error_ = other.error_;
      data_ = other.data_ != null ? other.data_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RespuestaCuenta Clone() {
      return new RespuestaCuenta(this);
    }

    /// <summary>Field number for the "Mensaje" field.</summary>
    public const int MensajeFieldNumber = 1;
    private string mensaje_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Mensaje {
      get { return mensaje_; }
      set {
        mensaje_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Error" field.</summary>
    public const int ErrorFieldNumber = 2;
    private bool error_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Error {
      get { return error_; }
      set {
        error_ = value;
      }
    }

    /// <summary>Field number for the "Data" field.</summary>
    public const int DataFieldNumber = 3;
    private global::EntryPoints.Grpc.Dtos.Protos.Cuentas.CuentaCompleta data_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::EntryPoints.Grpc.Dtos.Protos.Cuentas.CuentaCompleta Data {
      get { return data_; }
      set {
        data_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as RespuestaCuenta);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(RespuestaCuenta other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Mensaje != other.Mensaje) return false;
      if (Error != other.Error) return false;
      if (!object.Equals(Data, other.Data)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Mensaje.Length != 0) hash ^= Mensaje.GetHashCode();
      if (Error != false) hash ^= Error.GetHashCode();
      if (data_ != null) hash ^= Data.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Mensaje.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Mensaje);
      }
      if (Error != false) {
        output.WriteRawTag(16);
        output.WriteBool(Error);
      }
      if (data_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Data);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Mensaje.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Mensaje);
      }
      if (Error != false) {
        output.WriteRawTag(16);
        output.WriteBool(Error);
      }
      if (data_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Data);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Mensaje.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Mensaje);
      }
      if (Error != false) {
        size += 1 + 1;
      }
      if (data_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Data);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(RespuestaCuenta other) {
      if (other == null) {
        return;
      }
      if (other.Mensaje.Length != 0) {
        Mensaje = other.Mensaje;
      }
      if (other.Error != false) {
        Error = other.Error;
      }
      if (other.data_ != null) {
        if (data_ == null) {
          Data = new global::EntryPoints.Grpc.Dtos.Protos.Cuentas.CuentaCompleta();
        }
        Data.MergeFrom(other.Data);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Mensaje = input.ReadString();
            break;
          }
          case 16: {
            Error = input.ReadBool();
            break;
          }
          case 26: {
            if (data_ == null) {
              Data = new global::EntryPoints.Grpc.Dtos.Protos.Cuentas.CuentaCompleta();
            }
            input.ReadMessage(Data);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Mensaje = input.ReadString();
            break;
          }
          case 16: {
            Error = input.ReadBool();
            break;
          }
          case 26: {
            if (data_ == null) {
              Data = new global::EntryPoints.Grpc.Dtos.Protos.Cuentas.CuentaCompleta();
            }
            input.ReadMessage(Data);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class RespuestaListaCuentas : pb::IMessage<RespuestaListaCuentas>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<RespuestaListaCuentas> _parser = new pb::MessageParser<RespuestaListaCuentas>(() => new RespuestaListaCuentas());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<RespuestaListaCuentas> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::EntryPoints.Grpc.Dtos.Protos.Cuentas.CuentasReflection.Descriptor.MessageTypes[6]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RespuestaListaCuentas() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RespuestaListaCuentas(RespuestaListaCuentas other) : this() {
      mensaje_ = other.mensaje_;
      error_ = other.error_;
      data_ = other.data_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RespuestaListaCuentas Clone() {
      return new RespuestaListaCuentas(this);
    }

    /// <summary>Field number for the "Mensaje" field.</summary>
    public const int MensajeFieldNumber = 1;
    private string mensaje_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Mensaje {
      get { return mensaje_; }
      set {
        mensaje_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Error" field.</summary>
    public const int ErrorFieldNumber = 2;
    private bool error_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Error {
      get { return error_; }
      set {
        error_ = value;
      }
    }

    /// <summary>Field number for the "Data" field.</summary>
    public const int DataFieldNumber = 3;
    private static readonly pb::FieldCodec<global::EntryPoints.Grpc.Dtos.Protos.Cuentas.CuentaCompleta> _repeated_data_codec
        = pb::FieldCodec.ForMessage(26, global::EntryPoints.Grpc.Dtos.Protos.Cuentas.CuentaCompleta.Parser);
    private readonly pbc::RepeatedField<global::EntryPoints.Grpc.Dtos.Protos.Cuentas.CuentaCompleta> data_ = new pbc::RepeatedField<global::EntryPoints.Grpc.Dtos.Protos.Cuentas.CuentaCompleta>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::EntryPoints.Grpc.Dtos.Protos.Cuentas.CuentaCompleta> Data {
      get { return data_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as RespuestaListaCuentas);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(RespuestaListaCuentas other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Mensaje != other.Mensaje) return false;
      if (Error != other.Error) return false;
      if(!data_.Equals(other.data_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Mensaje.Length != 0) hash ^= Mensaje.GetHashCode();
      if (Error != false) hash ^= Error.GetHashCode();
      hash ^= data_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Mensaje.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Mensaje);
      }
      if (Error != false) {
        output.WriteRawTag(16);
        output.WriteBool(Error);
      }
      data_.WriteTo(output, _repeated_data_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Mensaje.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Mensaje);
      }
      if (Error != false) {
        output.WriteRawTag(16);
        output.WriteBool(Error);
      }
      data_.WriteTo(ref output, _repeated_data_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Mensaje.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Mensaje);
      }
      if (Error != false) {
        size += 1 + 1;
      }
      size += data_.CalculateSize(_repeated_data_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(RespuestaListaCuentas other) {
      if (other == null) {
        return;
      }
      if (other.Mensaje.Length != 0) {
        Mensaje = other.Mensaje;
      }
      if (other.Error != false) {
        Error = other.Error;
      }
      data_.Add(other.data_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Mensaje = input.ReadString();
            break;
          }
          case 16: {
            Error = input.ReadBool();
            break;
          }
          case 26: {
            data_.AddEntriesFrom(input, _repeated_data_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Mensaje = input.ReadString();
            break;
          }
          case 16: {
            Error = input.ReadBool();
            break;
          }
          case 26: {
            data_.AddEntriesFrom(ref input, _repeated_data_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class CuentaCompleta : pb::IMessage<CuentaCompleta>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<CuentaCompleta> _parser = new pb::MessageParser<CuentaCompleta>(() => new CuentaCompleta());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<CuentaCompleta> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::EntryPoints.Grpc.Dtos.Protos.Cuentas.CuentasReflection.Descriptor.MessageTypes[7]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CuentaCompleta() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CuentaCompleta(CuentaCompleta other) : this() {
      id_ = other.id_;
      numeroCuenta_ = other.numeroCuenta_;
      idCliente_ = other.idCliente_;
      tipoCuenta_ = other.tipoCuenta_;
      estadoCuenta_ = other.estadoCuenta_;
      saldo_ = other.saldo_;
      saldoDisponible_ = other.saldoDisponible_;
      gMF_ = other.gMF_;
      fechaCreacion_ = other.fechaCreacion_;
      fechaModificacion_ = other.fechaModificacion_;
      transacciones_ = other.transacciones_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CuentaCompleta Clone() {
      return new CuentaCompleta(this);
    }

    /// <summary>Field number for the "Id" field.</summary>
    public const int IdFieldNumber = 1;
    private string id_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Id {
      get { return id_; }
      set {
        id_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "NumeroCuenta" field.</summary>
    public const int NumeroCuentaFieldNumber = 2;
    private string numeroCuenta_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string NumeroCuenta {
      get { return numeroCuenta_; }
      set {
        numeroCuenta_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "IdCliente" field.</summary>
    public const int IdClienteFieldNumber = 3;
    private string idCliente_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string IdCliente {
      get { return idCliente_; }
      set {
        idCliente_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "TipoCuenta" field.</summary>
    public const int TipoCuentaFieldNumber = 4;
    private global::EntryPoints.Grpc.Dtos.Protos.Cuentas.TipoCuenta tipoCuenta_ = global::EntryPoints.Grpc.Dtos.Protos.Cuentas.TipoCuenta.Ahorro;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::EntryPoints.Grpc.Dtos.Protos.Cuentas.TipoCuenta TipoCuenta {
      get { return tipoCuenta_; }
      set {
        tipoCuenta_ = value;
      }
    }

    /// <summary>Field number for the "EstadoCuenta" field.</summary>
    public const int EstadoCuentaFieldNumber = 5;
    private global::EntryPoints.Grpc.Dtos.Protos.Cuentas.EstadoCuenta estadoCuenta_ = global::EntryPoints.Grpc.Dtos.Protos.Cuentas.EstadoCuenta.Activa;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::EntryPoints.Grpc.Dtos.Protos.Cuentas.EstadoCuenta EstadoCuenta {
      get { return estadoCuenta_; }
      set {
        estadoCuenta_ = value;
      }
    }

    /// <summary>Field number for the "Saldo" field.</summary>
    public const int SaldoFieldNumber = 6;
    private float saldo_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float Saldo {
      get { return saldo_; }
      set {
        saldo_ = value;
      }
    }

    /// <summary>Field number for the "SaldoDisponible" field.</summary>
    public const int SaldoDisponibleFieldNumber = 7;
    private float saldoDisponible_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float SaldoDisponible {
      get { return saldoDisponible_; }
      set {
        saldoDisponible_ = value;
      }
    }

    /// <summary>Field number for the "GMF" field.</summary>
    public const int GMFFieldNumber = 8;
    private bool gMF_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool GMF {
      get { return gMF_; }
      set {
        gMF_ = value;
      }
    }

    /// <summary>Field number for the "FechaCreacion" field.</summary>
    public const int FechaCreacionFieldNumber = 9;
    private string fechaCreacion_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string FechaCreacion {
      get { return fechaCreacion_; }
      set {
        fechaCreacion_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "FechaModificacion" field.</summary>
    public const int FechaModificacionFieldNumber = 10;
    private string fechaModificacion_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string FechaModificacion {
      get { return fechaModificacion_; }
      set {
        fechaModificacion_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Transacciones" field.</summary>
    public const int TransaccionesFieldNumber = 11;
    private static readonly pb::FieldCodec<global::EntryPoints.Grpc.Dtos.Protos.Cuentas.TransaccionProto> _repeated_transacciones_codec
        = pb::FieldCodec.ForMessage(90, global::EntryPoints.Grpc.Dtos.Protos.Cuentas.TransaccionProto.Parser);
    private readonly pbc::RepeatedField<global::EntryPoints.Grpc.Dtos.Protos.Cuentas.TransaccionProto> transacciones_ = new pbc::RepeatedField<global::EntryPoints.Grpc.Dtos.Protos.Cuentas.TransaccionProto>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::EntryPoints.Grpc.Dtos.Protos.Cuentas.TransaccionProto> Transacciones {
      get { return transacciones_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as CuentaCompleta);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(CuentaCompleta other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (NumeroCuenta != other.NumeroCuenta) return false;
      if (IdCliente != other.IdCliente) return false;
      if (TipoCuenta != other.TipoCuenta) return false;
      if (EstadoCuenta != other.EstadoCuenta) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Saldo, other.Saldo)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(SaldoDisponible, other.SaldoDisponible)) return false;
      if (GMF != other.GMF) return false;
      if (FechaCreacion != other.FechaCreacion) return false;
      if (FechaModificacion != other.FechaModificacion) return false;
      if(!transacciones_.Equals(other.transacciones_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Id.Length != 0) hash ^= Id.GetHashCode();
      if (NumeroCuenta.Length != 0) hash ^= NumeroCuenta.GetHashCode();
      if (IdCliente.Length != 0) hash ^= IdCliente.GetHashCode();
      if (TipoCuenta != global::EntryPoints.Grpc.Dtos.Protos.Cuentas.TipoCuenta.Ahorro) hash ^= TipoCuenta.GetHashCode();
      if (EstadoCuenta != global::EntryPoints.Grpc.Dtos.Protos.Cuentas.EstadoCuenta.Activa) hash ^= EstadoCuenta.GetHashCode();
      if (Saldo != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Saldo);
      if (SaldoDisponible != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(SaldoDisponible);
      if (GMF != false) hash ^= GMF.GetHashCode();
      if (FechaCreacion.Length != 0) hash ^= FechaCreacion.GetHashCode();
      if (FechaModificacion.Length != 0) hash ^= FechaModificacion.GetHashCode();
      hash ^= transacciones_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      if (NumeroCuenta.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(NumeroCuenta);
      }
      if (IdCliente.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(IdCliente);
      }
      if (TipoCuenta != global::EntryPoints.Grpc.Dtos.Protos.Cuentas.TipoCuenta.Ahorro) {
        output.WriteRawTag(32);
        output.WriteEnum((int) TipoCuenta);
      }
      if (EstadoCuenta != global::EntryPoints.Grpc.Dtos.Protos.Cuentas.EstadoCuenta.Activa) {
        output.WriteRawTag(40);
        output.WriteEnum((int) EstadoCuenta);
      }
      if (Saldo != 0F) {
        output.WriteRawTag(53);
        output.WriteFloat(Saldo);
      }
      if (SaldoDisponible != 0F) {
        output.WriteRawTag(61);
        output.WriteFloat(SaldoDisponible);
      }
      if (GMF != false) {
        output.WriteRawTag(64);
        output.WriteBool(GMF);
      }
      if (FechaCreacion.Length != 0) {
        output.WriteRawTag(74);
        output.WriteString(FechaCreacion);
      }
      if (FechaModificacion.Length != 0) {
        output.WriteRawTag(82);
        output.WriteString(FechaModificacion);
      }
      transacciones_.WriteTo(output, _repeated_transacciones_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      if (NumeroCuenta.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(NumeroCuenta);
      }
      if (IdCliente.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(IdCliente);
      }
      if (TipoCuenta != global::EntryPoints.Grpc.Dtos.Protos.Cuentas.TipoCuenta.Ahorro) {
        output.WriteRawTag(32);
        output.WriteEnum((int) TipoCuenta);
      }
      if (EstadoCuenta != global::EntryPoints.Grpc.Dtos.Protos.Cuentas.EstadoCuenta.Activa) {
        output.WriteRawTag(40);
        output.WriteEnum((int) EstadoCuenta);
      }
      if (Saldo != 0F) {
        output.WriteRawTag(53);
        output.WriteFloat(Saldo);
      }
      if (SaldoDisponible != 0F) {
        output.WriteRawTag(61);
        output.WriteFloat(SaldoDisponible);
      }
      if (GMF != false) {
        output.WriteRawTag(64);
        output.WriteBool(GMF);
      }
      if (FechaCreacion.Length != 0) {
        output.WriteRawTag(74);
        output.WriteString(FechaCreacion);
      }
      if (FechaModificacion.Length != 0) {
        output.WriteRawTag(82);
        output.WriteString(FechaModificacion);
      }
      transacciones_.WriteTo(ref output, _repeated_transacciones_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Id.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Id);
      }
      if (NumeroCuenta.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(NumeroCuenta);
      }
      if (IdCliente.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(IdCliente);
      }
      if (TipoCuenta != global::EntryPoints.Grpc.Dtos.Protos.Cuentas.TipoCuenta.Ahorro) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) TipoCuenta);
      }
      if (EstadoCuenta != global::EntryPoints.Grpc.Dtos.Protos.Cuentas.EstadoCuenta.Activa) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) EstadoCuenta);
      }
      if (Saldo != 0F) {
        size += 1 + 4;
      }
      if (SaldoDisponible != 0F) {
        size += 1 + 4;
      }
      if (GMF != false) {
        size += 1 + 1;
      }
      if (FechaCreacion.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(FechaCreacion);
      }
      if (FechaModificacion.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(FechaModificacion);
      }
      size += transacciones_.CalculateSize(_repeated_transacciones_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(CuentaCompleta other) {
      if (other == null) {
        return;
      }
      if (other.Id.Length != 0) {
        Id = other.Id;
      }
      if (other.NumeroCuenta.Length != 0) {
        NumeroCuenta = other.NumeroCuenta;
      }
      if (other.IdCliente.Length != 0) {
        IdCliente = other.IdCliente;
      }
      if (other.TipoCuenta != global::EntryPoints.Grpc.Dtos.Protos.Cuentas.TipoCuenta.Ahorro) {
        TipoCuenta = other.TipoCuenta;
      }
      if (other.EstadoCuenta != global::EntryPoints.Grpc.Dtos.Protos.Cuentas.EstadoCuenta.Activa) {
        EstadoCuenta = other.EstadoCuenta;
      }
      if (other.Saldo != 0F) {
        Saldo = other.Saldo;
      }
      if (other.SaldoDisponible != 0F) {
        SaldoDisponible = other.SaldoDisponible;
      }
      if (other.GMF != false) {
        GMF = other.GMF;
      }
      if (other.FechaCreacion.Length != 0) {
        FechaCreacion = other.FechaCreacion;
      }
      if (other.FechaModificacion.Length != 0) {
        FechaModificacion = other.FechaModificacion;
      }
      transacciones_.Add(other.transacciones_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
          case 18: {
            NumeroCuenta = input.ReadString();
            break;
          }
          case 26: {
            IdCliente = input.ReadString();
            break;
          }
          case 32: {
            TipoCuenta = (global::EntryPoints.Grpc.Dtos.Protos.Cuentas.TipoCuenta) input.ReadEnum();
            break;
          }
          case 40: {
            EstadoCuenta = (global::EntryPoints.Grpc.Dtos.Protos.Cuentas.EstadoCuenta) input.ReadEnum();
            break;
          }
          case 53: {
            Saldo = input.ReadFloat();
            break;
          }
          case 61: {
            SaldoDisponible = input.ReadFloat();
            break;
          }
          case 64: {
            GMF = input.ReadBool();
            break;
          }
          case 74: {
            FechaCreacion = input.ReadString();
            break;
          }
          case 82: {
            FechaModificacion = input.ReadString();
            break;
          }
          case 90: {
            transacciones_.AddEntriesFrom(input, _repeated_transacciones_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
          case 18: {
            NumeroCuenta = input.ReadString();
            break;
          }
          case 26: {
            IdCliente = input.ReadString();
            break;
          }
          case 32: {
            TipoCuenta = (global::EntryPoints.Grpc.Dtos.Protos.Cuentas.TipoCuenta) input.ReadEnum();
            break;
          }
          case 40: {
            EstadoCuenta = (global::EntryPoints.Grpc.Dtos.Protos.Cuentas.EstadoCuenta) input.ReadEnum();
            break;
          }
          case 53: {
            Saldo = input.ReadFloat();
            break;
          }
          case 61: {
            SaldoDisponible = input.ReadFloat();
            break;
          }
          case 64: {
            GMF = input.ReadBool();
            break;
          }
          case 74: {
            FechaCreacion = input.ReadString();
            break;
          }
          case 82: {
            FechaModificacion = input.ReadString();
            break;
          }
          case 90: {
            transacciones_.AddEntriesFrom(ref input, _repeated_transacciones_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
