// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: protos/Cuentas.proto
// </auto-generated>
#pragma warning disable 0414, 1591, 8981
#region Designer generated code

using grpc = global::Grpc.Core;

namespace EntryPoints.Grpc.Dtos.Protos.Cuentas {
  public static partial class CuentaService
  {
    static readonly string __ServiceName = "CuentaService";

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::EntryPoints.Grpc.Dtos.Protos.Cuentas.CuentaProto> __Marshaller_CuentaProto = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::EntryPoints.Grpc.Dtos.Protos.Cuentas.CuentaProto.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::EntryPoints.Grpc.Dtos.Protos.Cuentas.RespuestaCuenta> __Marshaller_RespuestaCuenta = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::EntryPoints.Grpc.Dtos.Protos.Cuentas.RespuestaCuenta.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::EntryPoints.Grpc.Dtos.Protos.Cuentas.CuentaRequest> __Marshaller_CuentaRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::EntryPoints.Grpc.Dtos.Protos.Cuentas.CuentaRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::EntryPoints.Grpc.Dtos.Protos.Cuentas.CuentaCompleta> __Marshaller_CuentaCompleta = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::EntryPoints.Grpc.Dtos.Protos.Cuentas.CuentaCompleta.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::EntryPoints.Grpc.Dtos.Protos.Cuentas.NumeroCuentaRequest> __Marshaller_NumeroCuentaRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::EntryPoints.Grpc.Dtos.Protos.Cuentas.NumeroCuentaRequest.Parser));

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::EntryPoints.Grpc.Dtos.Protos.Cuentas.CuentaProto, global::EntryPoints.Grpc.Dtos.Protos.Cuentas.RespuestaCuenta> __Method_CrearCuenta = new grpc::Method<global::EntryPoints.Grpc.Dtos.Protos.Cuentas.CuentaProto, global::EntryPoints.Grpc.Dtos.Protos.Cuentas.RespuestaCuenta>(
        grpc::MethodType.Unary,
        __ServiceName,
        "CrearCuenta",
        __Marshaller_CuentaProto,
        __Marshaller_RespuestaCuenta);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::EntryPoints.Grpc.Dtos.Protos.Cuentas.CuentaRequest, global::EntryPoints.Grpc.Dtos.Protos.Cuentas.RespuestaCuenta> __Method_ObtenerCuentaId = new grpc::Method<global::EntryPoints.Grpc.Dtos.Protos.Cuentas.CuentaRequest, global::EntryPoints.Grpc.Dtos.Protos.Cuentas.RespuestaCuenta>(
        grpc::MethodType.Unary,
        __ServiceName,
        "ObtenerCuentaId",
        __Marshaller_CuentaRequest,
        __Marshaller_RespuestaCuenta);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::EntryPoints.Grpc.Dtos.Protos.Cuentas.CuentaCompleta, global::EntryPoints.Grpc.Dtos.Protos.Cuentas.RespuestaCuenta> __Method_ActualizarCuenta = new grpc::Method<global::EntryPoints.Grpc.Dtos.Protos.Cuentas.CuentaCompleta, global::EntryPoints.Grpc.Dtos.Protos.Cuentas.RespuestaCuenta>(
        grpc::MethodType.Unary,
        __ServiceName,
        "ActualizarCuenta",
        __Marshaller_CuentaCompleta,
        __Marshaller_RespuestaCuenta);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::EntryPoints.Grpc.Dtos.Protos.Cuentas.CuentaRequest, global::EntryPoints.Grpc.Dtos.Protos.Cuentas.RespuestaCuenta> __Method_CancelarCuenta = new grpc::Method<global::EntryPoints.Grpc.Dtos.Protos.Cuentas.CuentaRequest, global::EntryPoints.Grpc.Dtos.Protos.Cuentas.RespuestaCuenta>(
        grpc::MethodType.Unary,
        __ServiceName,
        "CancelarCuenta",
        __Marshaller_CuentaRequest,
        __Marshaller_RespuestaCuenta);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::EntryPoints.Grpc.Dtos.Protos.Cuentas.CuentaRequest, global::EntryPoints.Grpc.Dtos.Protos.Cuentas.RespuestaCuenta> __Method_ActivarCuentaAsync = new grpc::Method<global::EntryPoints.Grpc.Dtos.Protos.Cuentas.CuentaRequest, global::EntryPoints.Grpc.Dtos.Protos.Cuentas.RespuestaCuenta>(
        grpc::MethodType.Unary,
        __ServiceName,
        "ActivarCuentaAsync",
        __Marshaller_CuentaRequest,
        __Marshaller_RespuestaCuenta);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::EntryPoints.Grpc.Dtos.Protos.Cuentas.NumeroCuentaRequest, global::EntryPoints.Grpc.Dtos.Protos.Cuentas.RespuestaCuenta> __Method_ObtenerCuentaNumero = new grpc::Method<global::EntryPoints.Grpc.Dtos.Protos.Cuentas.NumeroCuentaRequest, global::EntryPoints.Grpc.Dtos.Protos.Cuentas.RespuestaCuenta>(
        grpc::MethodType.Unary,
        __ServiceName,
        "ObtenerCuentaNumero",
        __Marshaller_NumeroCuentaRequest,
        __Marshaller_RespuestaCuenta);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::EntryPoints.Grpc.Dtos.Protos.Cuentas.CuentaRequest, global::EntryPoints.Grpc.Dtos.Protos.Cuentas.RespuestaCuenta> __Method_InactivarCuentaAsync = new grpc::Method<global::EntryPoints.Grpc.Dtos.Protos.Cuentas.CuentaRequest, global::EntryPoints.Grpc.Dtos.Protos.Cuentas.RespuestaCuenta>(
        grpc::MethodType.Unary,
        __ServiceName,
        "InactivarCuentaAsync",
        __Marshaller_CuentaRequest,
        __Marshaller_RespuestaCuenta);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::EntryPoints.Grpc.Dtos.Protos.Cuentas.CuentasReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of CuentaService</summary>
    [grpc::BindServiceMethod(typeof(CuentaService), "BindService")]
    public abstract partial class CuentaServiceBase
    {
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::EntryPoints.Grpc.Dtos.Protos.Cuentas.RespuestaCuenta> CrearCuenta(global::EntryPoints.Grpc.Dtos.Protos.Cuentas.CuentaProto request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::EntryPoints.Grpc.Dtos.Protos.Cuentas.RespuestaCuenta> ObtenerCuentaId(global::EntryPoints.Grpc.Dtos.Protos.Cuentas.CuentaRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::EntryPoints.Grpc.Dtos.Protos.Cuentas.RespuestaCuenta> ActualizarCuenta(global::EntryPoints.Grpc.Dtos.Protos.Cuentas.CuentaCompleta request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::EntryPoints.Grpc.Dtos.Protos.Cuentas.RespuestaCuenta> CancelarCuenta(global::EntryPoints.Grpc.Dtos.Protos.Cuentas.CuentaRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::EntryPoints.Grpc.Dtos.Protos.Cuentas.RespuestaCuenta> ActivarCuentaAsync(global::EntryPoints.Grpc.Dtos.Protos.Cuentas.CuentaRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::EntryPoints.Grpc.Dtos.Protos.Cuentas.RespuestaCuenta> ObtenerCuentaNumero(global::EntryPoints.Grpc.Dtos.Protos.Cuentas.NumeroCuentaRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::EntryPoints.Grpc.Dtos.Protos.Cuentas.RespuestaCuenta> InactivarCuentaAsync(global::EntryPoints.Grpc.Dtos.Protos.Cuentas.CuentaRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for CuentaService</summary>
    public partial class CuentaServiceClient : grpc::ClientBase<CuentaServiceClient>
    {
      /// <summary>Creates a new client for CuentaService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public CuentaServiceClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for CuentaService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public CuentaServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected CuentaServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected CuentaServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::EntryPoints.Grpc.Dtos.Protos.Cuentas.RespuestaCuenta CrearCuenta(global::EntryPoints.Grpc.Dtos.Protos.Cuentas.CuentaProto request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CrearCuenta(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::EntryPoints.Grpc.Dtos.Protos.Cuentas.RespuestaCuenta CrearCuenta(global::EntryPoints.Grpc.Dtos.Protos.Cuentas.CuentaProto request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_CrearCuenta, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::EntryPoints.Grpc.Dtos.Protos.Cuentas.RespuestaCuenta> CrearCuentaAsync(global::EntryPoints.Grpc.Dtos.Protos.Cuentas.CuentaProto request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CrearCuentaAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::EntryPoints.Grpc.Dtos.Protos.Cuentas.RespuestaCuenta> CrearCuentaAsync(global::EntryPoints.Grpc.Dtos.Protos.Cuentas.CuentaProto request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_CrearCuenta, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::EntryPoints.Grpc.Dtos.Protos.Cuentas.RespuestaCuenta ObtenerCuentaId(global::EntryPoints.Grpc.Dtos.Protos.Cuentas.CuentaRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ObtenerCuentaId(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::EntryPoints.Grpc.Dtos.Protos.Cuentas.RespuestaCuenta ObtenerCuentaId(global::EntryPoints.Grpc.Dtos.Protos.Cuentas.CuentaRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_ObtenerCuentaId, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::EntryPoints.Grpc.Dtos.Protos.Cuentas.RespuestaCuenta> ObtenerCuentaIdAsync(global::EntryPoints.Grpc.Dtos.Protos.Cuentas.CuentaRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ObtenerCuentaIdAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::EntryPoints.Grpc.Dtos.Protos.Cuentas.RespuestaCuenta> ObtenerCuentaIdAsync(global::EntryPoints.Grpc.Dtos.Protos.Cuentas.CuentaRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_ObtenerCuentaId, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::EntryPoints.Grpc.Dtos.Protos.Cuentas.RespuestaCuenta ActualizarCuenta(global::EntryPoints.Grpc.Dtos.Protos.Cuentas.CuentaCompleta request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ActualizarCuenta(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::EntryPoints.Grpc.Dtos.Protos.Cuentas.RespuestaCuenta ActualizarCuenta(global::EntryPoints.Grpc.Dtos.Protos.Cuentas.CuentaCompleta request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_ActualizarCuenta, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::EntryPoints.Grpc.Dtos.Protos.Cuentas.RespuestaCuenta> ActualizarCuentaAsync(global::EntryPoints.Grpc.Dtos.Protos.Cuentas.CuentaCompleta request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ActualizarCuentaAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::EntryPoints.Grpc.Dtos.Protos.Cuentas.RespuestaCuenta> ActualizarCuentaAsync(global::EntryPoints.Grpc.Dtos.Protos.Cuentas.CuentaCompleta request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_ActualizarCuenta, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::EntryPoints.Grpc.Dtos.Protos.Cuentas.RespuestaCuenta CancelarCuenta(global::EntryPoints.Grpc.Dtos.Protos.Cuentas.CuentaRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CancelarCuenta(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::EntryPoints.Grpc.Dtos.Protos.Cuentas.RespuestaCuenta CancelarCuenta(global::EntryPoints.Grpc.Dtos.Protos.Cuentas.CuentaRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_CancelarCuenta, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::EntryPoints.Grpc.Dtos.Protos.Cuentas.RespuestaCuenta> CancelarCuentaAsync(global::EntryPoints.Grpc.Dtos.Protos.Cuentas.CuentaRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CancelarCuentaAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::EntryPoints.Grpc.Dtos.Protos.Cuentas.RespuestaCuenta> CancelarCuentaAsync(global::EntryPoints.Grpc.Dtos.Protos.Cuentas.CuentaRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_CancelarCuenta, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::EntryPoints.Grpc.Dtos.Protos.Cuentas.RespuestaCuenta ActivarCuentaAsync(global::EntryPoints.Grpc.Dtos.Protos.Cuentas.CuentaRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ActivarCuentaAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::EntryPoints.Grpc.Dtos.Protos.Cuentas.RespuestaCuenta ActivarCuentaAsync(global::EntryPoints.Grpc.Dtos.Protos.Cuentas.CuentaRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_ActivarCuentaAsync, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::EntryPoints.Grpc.Dtos.Protos.Cuentas.RespuestaCuenta> ActivarCuentaAsyncAsync(global::EntryPoints.Grpc.Dtos.Protos.Cuentas.CuentaRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ActivarCuentaAsyncAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::EntryPoints.Grpc.Dtos.Protos.Cuentas.RespuestaCuenta> ActivarCuentaAsyncAsync(global::EntryPoints.Grpc.Dtos.Protos.Cuentas.CuentaRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_ActivarCuentaAsync, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::EntryPoints.Grpc.Dtos.Protos.Cuentas.RespuestaCuenta ObtenerCuentaNumero(global::EntryPoints.Grpc.Dtos.Protos.Cuentas.NumeroCuentaRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ObtenerCuentaNumero(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::EntryPoints.Grpc.Dtos.Protos.Cuentas.RespuestaCuenta ObtenerCuentaNumero(global::EntryPoints.Grpc.Dtos.Protos.Cuentas.NumeroCuentaRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_ObtenerCuentaNumero, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::EntryPoints.Grpc.Dtos.Protos.Cuentas.RespuestaCuenta> ObtenerCuentaNumeroAsync(global::EntryPoints.Grpc.Dtos.Protos.Cuentas.NumeroCuentaRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ObtenerCuentaNumeroAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::EntryPoints.Grpc.Dtos.Protos.Cuentas.RespuestaCuenta> ObtenerCuentaNumeroAsync(global::EntryPoints.Grpc.Dtos.Protos.Cuentas.NumeroCuentaRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_ObtenerCuentaNumero, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::EntryPoints.Grpc.Dtos.Protos.Cuentas.RespuestaCuenta InactivarCuentaAsync(global::EntryPoints.Grpc.Dtos.Protos.Cuentas.CuentaRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return InactivarCuentaAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::EntryPoints.Grpc.Dtos.Protos.Cuentas.RespuestaCuenta InactivarCuentaAsync(global::EntryPoints.Grpc.Dtos.Protos.Cuentas.CuentaRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_InactivarCuentaAsync, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::EntryPoints.Grpc.Dtos.Protos.Cuentas.RespuestaCuenta> InactivarCuentaAsyncAsync(global::EntryPoints.Grpc.Dtos.Protos.Cuentas.CuentaRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return InactivarCuentaAsyncAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::EntryPoints.Grpc.Dtos.Protos.Cuentas.RespuestaCuenta> InactivarCuentaAsyncAsync(global::EntryPoints.Grpc.Dtos.Protos.Cuentas.CuentaRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_InactivarCuentaAsync, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected override CuentaServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new CuentaServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static grpc::ServerServiceDefinition BindService(CuentaServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_CrearCuenta, serviceImpl.CrearCuenta)
          .AddMethod(__Method_ObtenerCuentaId, serviceImpl.ObtenerCuentaId)
          .AddMethod(__Method_ActualizarCuenta, serviceImpl.ActualizarCuenta)
          .AddMethod(__Method_CancelarCuenta, serviceImpl.CancelarCuenta)
          .AddMethod(__Method_ActivarCuentaAsync, serviceImpl.ActivarCuentaAsync)
          .AddMethod(__Method_ObtenerCuentaNumero, serviceImpl.ObtenerCuentaNumero)
          .AddMethod(__Method_InactivarCuentaAsync, serviceImpl.InactivarCuentaAsync).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static void BindService(grpc::ServiceBinderBase serviceBinder, CuentaServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_CrearCuenta, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::EntryPoints.Grpc.Dtos.Protos.Cuentas.CuentaProto, global::EntryPoints.Grpc.Dtos.Protos.Cuentas.RespuestaCuenta>(serviceImpl.CrearCuenta));
      serviceBinder.AddMethod(__Method_ObtenerCuentaId, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::EntryPoints.Grpc.Dtos.Protos.Cuentas.CuentaRequest, global::EntryPoints.Grpc.Dtos.Protos.Cuentas.RespuestaCuenta>(serviceImpl.ObtenerCuentaId));
      serviceBinder.AddMethod(__Method_ActualizarCuenta, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::EntryPoints.Grpc.Dtos.Protos.Cuentas.CuentaCompleta, global::EntryPoints.Grpc.Dtos.Protos.Cuentas.RespuestaCuenta>(serviceImpl.ActualizarCuenta));
      serviceBinder.AddMethod(__Method_CancelarCuenta, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::EntryPoints.Grpc.Dtos.Protos.Cuentas.CuentaRequest, global::EntryPoints.Grpc.Dtos.Protos.Cuentas.RespuestaCuenta>(serviceImpl.CancelarCuenta));
      serviceBinder.AddMethod(__Method_ActivarCuentaAsync, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::EntryPoints.Grpc.Dtos.Protos.Cuentas.CuentaRequest, global::EntryPoints.Grpc.Dtos.Protos.Cuentas.RespuestaCuenta>(serviceImpl.ActivarCuentaAsync));
      serviceBinder.AddMethod(__Method_ObtenerCuentaNumero, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::EntryPoints.Grpc.Dtos.Protos.Cuentas.NumeroCuentaRequest, global::EntryPoints.Grpc.Dtos.Protos.Cuentas.RespuestaCuenta>(serviceImpl.ObtenerCuentaNumero));
      serviceBinder.AddMethod(__Method_InactivarCuentaAsync, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::EntryPoints.Grpc.Dtos.Protos.Cuentas.CuentaRequest, global::EntryPoints.Grpc.Dtos.Protos.Cuentas.RespuestaCuenta>(serviceImpl.InactivarCuentaAsync));
    }

  }
}
#endregion
