// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: protos/Transaccion.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace EntryPoints.Grpc.Dtos.Protos {

  /// <summary>Holder for reflection information generated from protos/Transaccion.proto</summary>
  public static partial class TransaccionReflection {

    #region Descriptor
    /// <summary>File descriptor for protos/Transaccion.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static TransaccionReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Chhwcm90b3MvVHJhbnNhY2Npb24ucHJvdG8ihgEKElRyYW5zYWNjaW9uUmVx",
            "dWVzdBIXCg9JZEN1ZW50YUVtaXNvcmEYASABKAkSGQoRSWRDdWVudGFSZWNl",
            "cHRvcmEYAiABKAkSLQoPVGlwb1RyYW5zYWNjaW9uGAMgASgOMhQuVGlwb1Ry",
            "YW5zYWNjaW9uRW51bRINCgVWYWxvchgEIAEoAiJWChRUcmFuc2FjY2lvblJl",
            "c3B1ZXN0YRIPCgdNZW5zYWplGAEgASgJEg0KBUVycm9yGAIgASgIEh4KBERh",
            "dGEYAyABKAsyEC5UcmFuc2FjY2lvbkluZm8iyQEKD1RyYW5zYWNjaW9uSW5m",
            "bxIXCg9JZEN1ZW50YUVtaXNvcmEYASABKAkSGQoRSWRDdWVudGFSZWNlcHRv",
            "cmEYAiABKAkSLQoPVGlwb1RyYW5zYWNjaW9uGAMgASgOMhQuVGlwb1RyYW5z",
            "YWNjaW9uRW51bRINCgVWYWxvchgEIAEoAhIXCg9GZWNoYU1vdmltaWVudG8Y",
            "BSABKAkSKwoOVGlwb01vdmltaWVudG8YBiABKA4yEy5UaXBvTW92aW1pZW50",
            "b0VudW0qRgoTVGlwb1RyYW5zYWNjaW9uRW51bRIRCg1UUkFOU0ZFUkVOQ0lB",
            "EAASEAoMQ09OU0lHTkFDSU9OEAESCgoGUkVUSVJPEAIqLQoSVGlwb01vdmlt",
            "aWVudG9FbnVtEgsKB0NSRURJVE8QABIKCgZERUJJVE8QATJXChJUcmFuc2Fj",
            "Y2lvblNlcnZpY2USQQoTUmVhbGl6YXJUcmFuc2FjY2lvbhITLlRyYW5zYWNj",
            "aW9uUmVxdWVzdBoVLlRyYW5zYWNjaW9uUmVzcHVlc3RhQh+qAhxFbnRyeVBv",
            "aW50cy5HcnBjLkR0b3MuUHJvdG9zYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::EntryPoints.Grpc.Dtos.Protos.TipoTransaccionEnum), typeof(global::EntryPoints.Grpc.Dtos.Protos.TipoMovimientoEnum), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::EntryPoints.Grpc.Dtos.Protos.TransaccionRequest), global::EntryPoints.Grpc.Dtos.Protos.TransaccionRequest.Parser, new[]{ "IdCuentaEmisora", "IdCuentaReceptora", "TipoTransaccion", "Valor" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::EntryPoints.Grpc.Dtos.Protos.TransaccionRespuesta), global::EntryPoints.Grpc.Dtos.Protos.TransaccionRespuesta.Parser, new[]{ "Mensaje", "Error", "Data" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::EntryPoints.Grpc.Dtos.Protos.TransaccionInfo), global::EntryPoints.Grpc.Dtos.Protos.TransaccionInfo.Parser, new[]{ "IdCuentaEmisora", "IdCuentaReceptora", "TipoTransaccion", "Valor", "FechaMovimiento", "TipoMovimiento" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum TipoTransaccionEnum {
    [pbr::OriginalName("TRANSFERENCIA")] Transferencia = 0,
    [pbr::OriginalName("CONSIGNACION")] Consignacion = 1,
    [pbr::OriginalName("RETIRO")] Retiro = 2,
  }

  public enum TipoMovimientoEnum {
    [pbr::OriginalName("CREDITO")] Credito = 0,
    [pbr::OriginalName("DEBITO")] Debito = 1,
  }

  #endregion

  #region Messages
  public sealed partial class TransaccionRequest : pb::IMessage<TransaccionRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<TransaccionRequest> _parser = new pb::MessageParser<TransaccionRequest>(() => new TransaccionRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<TransaccionRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::EntryPoints.Grpc.Dtos.Protos.TransaccionReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TransaccionRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TransaccionRequest(TransaccionRequest other) : this() {
      idCuentaEmisora_ = other.idCuentaEmisora_;
      idCuentaReceptora_ = other.idCuentaReceptora_;
      tipoTransaccion_ = other.tipoTransaccion_;
      valor_ = other.valor_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TransaccionRequest Clone() {
      return new TransaccionRequest(this);
    }

    /// <summary>Field number for the "IdCuentaEmisora" field.</summary>
    public const int IdCuentaEmisoraFieldNumber = 1;
    private string idCuentaEmisora_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string IdCuentaEmisora {
      get { return idCuentaEmisora_; }
      set {
        idCuentaEmisora_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "IdCuentaReceptora" field.</summary>
    public const int IdCuentaReceptoraFieldNumber = 2;
    private string idCuentaReceptora_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string IdCuentaReceptora {
      get { return idCuentaReceptora_; }
      set {
        idCuentaReceptora_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "TipoTransaccion" field.</summary>
    public const int TipoTransaccionFieldNumber = 3;
    private global::EntryPoints.Grpc.Dtos.Protos.TipoTransaccionEnum tipoTransaccion_ = global::EntryPoints.Grpc.Dtos.Protos.TipoTransaccionEnum.Transferencia;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::EntryPoints.Grpc.Dtos.Protos.TipoTransaccionEnum TipoTransaccion {
      get { return tipoTransaccion_; }
      set {
        tipoTransaccion_ = value;
      }
    }

    /// <summary>Field number for the "Valor" field.</summary>
    public const int ValorFieldNumber = 4;
    private float valor_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float Valor {
      get { return valor_; }
      set {
        valor_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as TransaccionRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(TransaccionRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (IdCuentaEmisora != other.IdCuentaEmisora) return false;
      if (IdCuentaReceptora != other.IdCuentaReceptora) return false;
      if (TipoTransaccion != other.TipoTransaccion) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Valor, other.Valor)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (IdCuentaEmisora.Length != 0) hash ^= IdCuentaEmisora.GetHashCode();
      if (IdCuentaReceptora.Length != 0) hash ^= IdCuentaReceptora.GetHashCode();
      if (TipoTransaccion != global::EntryPoints.Grpc.Dtos.Protos.TipoTransaccionEnum.Transferencia) hash ^= TipoTransaccion.GetHashCode();
      if (Valor != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Valor);
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (IdCuentaEmisora.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(IdCuentaEmisora);
      }
      if (IdCuentaReceptora.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(IdCuentaReceptora);
      }
      if (TipoTransaccion != global::EntryPoints.Grpc.Dtos.Protos.TipoTransaccionEnum.Transferencia) {
        output.WriteRawTag(24);
        output.WriteEnum((int) TipoTransaccion);
      }
      if (Valor != 0F) {
        output.WriteRawTag(37);
        output.WriteFloat(Valor);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (IdCuentaEmisora.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(IdCuentaEmisora);
      }
      if (IdCuentaReceptora.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(IdCuentaReceptora);
      }
      if (TipoTransaccion != global::EntryPoints.Grpc.Dtos.Protos.TipoTransaccionEnum.Transferencia) {
        output.WriteRawTag(24);
        output.WriteEnum((int) TipoTransaccion);
      }
      if (Valor != 0F) {
        output.WriteRawTag(37);
        output.WriteFloat(Valor);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (IdCuentaEmisora.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(IdCuentaEmisora);
      }
      if (IdCuentaReceptora.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(IdCuentaReceptora);
      }
      if (TipoTransaccion != global::EntryPoints.Grpc.Dtos.Protos.TipoTransaccionEnum.Transferencia) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) TipoTransaccion);
      }
      if (Valor != 0F) {
        size += 1 + 4;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(TransaccionRequest other) {
      if (other == null) {
        return;
      }
      if (other.IdCuentaEmisora.Length != 0) {
        IdCuentaEmisora = other.IdCuentaEmisora;
      }
      if (other.IdCuentaReceptora.Length != 0) {
        IdCuentaReceptora = other.IdCuentaReceptora;
      }
      if (other.TipoTransaccion != global::EntryPoints.Grpc.Dtos.Protos.TipoTransaccionEnum.Transferencia) {
        TipoTransaccion = other.TipoTransaccion;
      }
      if (other.Valor != 0F) {
        Valor = other.Valor;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            IdCuentaEmisora = input.ReadString();
            break;
          }
          case 18: {
            IdCuentaReceptora = input.ReadString();
            break;
          }
          case 24: {
            TipoTransaccion = (global::EntryPoints.Grpc.Dtos.Protos.TipoTransaccionEnum) input.ReadEnum();
            break;
          }
          case 37: {
            Valor = input.ReadFloat();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            IdCuentaEmisora = input.ReadString();
            break;
          }
          case 18: {
            IdCuentaReceptora = input.ReadString();
            break;
          }
          case 24: {
            TipoTransaccion = (global::EntryPoints.Grpc.Dtos.Protos.TipoTransaccionEnum) input.ReadEnum();
            break;
          }
          case 37: {
            Valor = input.ReadFloat();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class TransaccionRespuesta : pb::IMessage<TransaccionRespuesta>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<TransaccionRespuesta> _parser = new pb::MessageParser<TransaccionRespuesta>(() => new TransaccionRespuesta());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<TransaccionRespuesta> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::EntryPoints.Grpc.Dtos.Protos.TransaccionReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TransaccionRespuesta() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TransaccionRespuesta(TransaccionRespuesta other) : this() {
      mensaje_ = other.mensaje_;
      error_ = other.error_;
      data_ = other.data_ != null ? other.data_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TransaccionRespuesta Clone() {
      return new TransaccionRespuesta(this);
    }

    /// <summary>Field number for the "Mensaje" field.</summary>
    public const int MensajeFieldNumber = 1;
    private string mensaje_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Mensaje {
      get { return mensaje_; }
      set {
        mensaje_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Error" field.</summary>
    public const int ErrorFieldNumber = 2;
    private bool error_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Error {
      get { return error_; }
      set {
        error_ = value;
      }
    }

    /// <summary>Field number for the "Data" field.</summary>
    public const int DataFieldNumber = 3;
    private global::EntryPoints.Grpc.Dtos.Protos.TransaccionInfo data_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::EntryPoints.Grpc.Dtos.Protos.TransaccionInfo Data {
      get { return data_; }
      set {
        data_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as TransaccionRespuesta);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(TransaccionRespuesta other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Mensaje != other.Mensaje) return false;
      if (Error != other.Error) return false;
      if (!object.Equals(Data, other.Data)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Mensaje.Length != 0) hash ^= Mensaje.GetHashCode();
      if (Error != false) hash ^= Error.GetHashCode();
      if (data_ != null) hash ^= Data.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Mensaje.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Mensaje);
      }
      if (Error != false) {
        output.WriteRawTag(16);
        output.WriteBool(Error);
      }
      if (data_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Data);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Mensaje.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Mensaje);
      }
      if (Error != false) {
        output.WriteRawTag(16);
        output.WriteBool(Error);
      }
      if (data_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Data);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Mensaje.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Mensaje);
      }
      if (Error != false) {
        size += 1 + 1;
      }
      if (data_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Data);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(TransaccionRespuesta other) {
      if (other == null) {
        return;
      }
      if (other.Mensaje.Length != 0) {
        Mensaje = other.Mensaje;
      }
      if (other.Error != false) {
        Error = other.Error;
      }
      if (other.data_ != null) {
        if (data_ == null) {
          Data = new global::EntryPoints.Grpc.Dtos.Protos.TransaccionInfo();
        }
        Data.MergeFrom(other.Data);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Mensaje = input.ReadString();
            break;
          }
          case 16: {
            Error = input.ReadBool();
            break;
          }
          case 26: {
            if (data_ == null) {
              Data = new global::EntryPoints.Grpc.Dtos.Protos.TransaccionInfo();
            }
            input.ReadMessage(Data);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Mensaje = input.ReadString();
            break;
          }
          case 16: {
            Error = input.ReadBool();
            break;
          }
          case 26: {
            if (data_ == null) {
              Data = new global::EntryPoints.Grpc.Dtos.Protos.TransaccionInfo();
            }
            input.ReadMessage(Data);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class TransaccionInfo : pb::IMessage<TransaccionInfo>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<TransaccionInfo> _parser = new pb::MessageParser<TransaccionInfo>(() => new TransaccionInfo());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<TransaccionInfo> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::EntryPoints.Grpc.Dtos.Protos.TransaccionReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TransaccionInfo() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TransaccionInfo(TransaccionInfo other) : this() {
      idCuentaEmisora_ = other.idCuentaEmisora_;
      idCuentaReceptora_ = other.idCuentaReceptora_;
      tipoTransaccion_ = other.tipoTransaccion_;
      valor_ = other.valor_;
      fechaMovimiento_ = other.fechaMovimiento_;
      tipoMovimiento_ = other.tipoMovimiento_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TransaccionInfo Clone() {
      return new TransaccionInfo(this);
    }

    /// <summary>Field number for the "IdCuentaEmisora" field.</summary>
    public const int IdCuentaEmisoraFieldNumber = 1;
    private string idCuentaEmisora_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string IdCuentaEmisora {
      get { return idCuentaEmisora_; }
      set {
        idCuentaEmisora_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "IdCuentaReceptora" field.</summary>
    public const int IdCuentaReceptoraFieldNumber = 2;
    private string idCuentaReceptora_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string IdCuentaReceptora {
      get { return idCuentaReceptora_; }
      set {
        idCuentaReceptora_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "TipoTransaccion" field.</summary>
    public const int TipoTransaccionFieldNumber = 3;
    private global::EntryPoints.Grpc.Dtos.Protos.TipoTransaccionEnum tipoTransaccion_ = global::EntryPoints.Grpc.Dtos.Protos.TipoTransaccionEnum.Transferencia;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::EntryPoints.Grpc.Dtos.Protos.TipoTransaccionEnum TipoTransaccion {
      get { return tipoTransaccion_; }
      set {
        tipoTransaccion_ = value;
      }
    }

    /// <summary>Field number for the "Valor" field.</summary>
    public const int ValorFieldNumber = 4;
    private float valor_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float Valor {
      get { return valor_; }
      set {
        valor_ = value;
      }
    }

    /// <summary>Field number for the "FechaMovimiento" field.</summary>
    public const int FechaMovimientoFieldNumber = 5;
    private string fechaMovimiento_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string FechaMovimiento {
      get { return fechaMovimiento_; }
      set {
        fechaMovimiento_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "TipoMovimiento" field.</summary>
    public const int TipoMovimientoFieldNumber = 6;
    private global::EntryPoints.Grpc.Dtos.Protos.TipoMovimientoEnum tipoMovimiento_ = global::EntryPoints.Grpc.Dtos.Protos.TipoMovimientoEnum.Credito;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::EntryPoints.Grpc.Dtos.Protos.TipoMovimientoEnum TipoMovimiento {
      get { return tipoMovimiento_; }
      set {
        tipoMovimiento_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as TransaccionInfo);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(TransaccionInfo other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (IdCuentaEmisora != other.IdCuentaEmisora) return false;
      if (IdCuentaReceptora != other.IdCuentaReceptora) return false;
      if (TipoTransaccion != other.TipoTransaccion) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Valor, other.Valor)) return false;
      if (FechaMovimiento != other.FechaMovimiento) return false;
      if (TipoMovimiento != other.TipoMovimiento) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (IdCuentaEmisora.Length != 0) hash ^= IdCuentaEmisora.GetHashCode();
      if (IdCuentaReceptora.Length != 0) hash ^= IdCuentaReceptora.GetHashCode();
      if (TipoTransaccion != global::EntryPoints.Grpc.Dtos.Protos.TipoTransaccionEnum.Transferencia) hash ^= TipoTransaccion.GetHashCode();
      if (Valor != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Valor);
      if (FechaMovimiento.Length != 0) hash ^= FechaMovimiento.GetHashCode();
      if (TipoMovimiento != global::EntryPoints.Grpc.Dtos.Protos.TipoMovimientoEnum.Credito) hash ^= TipoMovimiento.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (IdCuentaEmisora.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(IdCuentaEmisora);
      }
      if (IdCuentaReceptora.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(IdCuentaReceptora);
      }
      if (TipoTransaccion != global::EntryPoints.Grpc.Dtos.Protos.TipoTransaccionEnum.Transferencia) {
        output.WriteRawTag(24);
        output.WriteEnum((int) TipoTransaccion);
      }
      if (Valor != 0F) {
        output.WriteRawTag(37);
        output.WriteFloat(Valor);
      }
      if (FechaMovimiento.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(FechaMovimiento);
      }
      if (TipoMovimiento != global::EntryPoints.Grpc.Dtos.Protos.TipoMovimientoEnum.Credito) {
        output.WriteRawTag(48);
        output.WriteEnum((int) TipoMovimiento);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (IdCuentaEmisora.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(IdCuentaEmisora);
      }
      if (IdCuentaReceptora.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(IdCuentaReceptora);
      }
      if (TipoTransaccion != global::EntryPoints.Grpc.Dtos.Protos.TipoTransaccionEnum.Transferencia) {
        output.WriteRawTag(24);
        output.WriteEnum((int) TipoTransaccion);
      }
      if (Valor != 0F) {
        output.WriteRawTag(37);
        output.WriteFloat(Valor);
      }
      if (FechaMovimiento.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(FechaMovimiento);
      }
      if (TipoMovimiento != global::EntryPoints.Grpc.Dtos.Protos.TipoMovimientoEnum.Credito) {
        output.WriteRawTag(48);
        output.WriteEnum((int) TipoMovimiento);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (IdCuentaEmisora.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(IdCuentaEmisora);
      }
      if (IdCuentaReceptora.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(IdCuentaReceptora);
      }
      if (TipoTransaccion != global::EntryPoints.Grpc.Dtos.Protos.TipoTransaccionEnum.Transferencia) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) TipoTransaccion);
      }
      if (Valor != 0F) {
        size += 1 + 4;
      }
      if (FechaMovimiento.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(FechaMovimiento);
      }
      if (TipoMovimiento != global::EntryPoints.Grpc.Dtos.Protos.TipoMovimientoEnum.Credito) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) TipoMovimiento);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(TransaccionInfo other) {
      if (other == null) {
        return;
      }
      if (other.IdCuentaEmisora.Length != 0) {
        IdCuentaEmisora = other.IdCuentaEmisora;
      }
      if (other.IdCuentaReceptora.Length != 0) {
        IdCuentaReceptora = other.IdCuentaReceptora;
      }
      if (other.TipoTransaccion != global::EntryPoints.Grpc.Dtos.Protos.TipoTransaccionEnum.Transferencia) {
        TipoTransaccion = other.TipoTransaccion;
      }
      if (other.Valor != 0F) {
        Valor = other.Valor;
      }
      if (other.FechaMovimiento.Length != 0) {
        FechaMovimiento = other.FechaMovimiento;
      }
      if (other.TipoMovimiento != global::EntryPoints.Grpc.Dtos.Protos.TipoMovimientoEnum.Credito) {
        TipoMovimiento = other.TipoMovimiento;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            IdCuentaEmisora = input.ReadString();
            break;
          }
          case 18: {
            IdCuentaReceptora = input.ReadString();
            break;
          }
          case 24: {
            TipoTransaccion = (global::EntryPoints.Grpc.Dtos.Protos.TipoTransaccionEnum) input.ReadEnum();
            break;
          }
          case 37: {
            Valor = input.ReadFloat();
            break;
          }
          case 42: {
            FechaMovimiento = input.ReadString();
            break;
          }
          case 48: {
            TipoMovimiento = (global::EntryPoints.Grpc.Dtos.Protos.TipoMovimientoEnum) input.ReadEnum();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            IdCuentaEmisora = input.ReadString();
            break;
          }
          case 18: {
            IdCuentaReceptora = input.ReadString();
            break;
          }
          case 24: {
            TipoTransaccion = (global::EntryPoints.Grpc.Dtos.Protos.TipoTransaccionEnum) input.ReadEnum();
            break;
          }
          case 37: {
            Valor = input.ReadFloat();
            break;
          }
          case 42: {
            FechaMovimiento = input.ReadString();
            break;
          }
          case 48: {
            TipoMovimiento = (global::EntryPoints.Grpc.Dtos.Protos.TipoMovimientoEnum) input.ReadEnum();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
